- name: Deploy VMs
  hosts: localhost
  vars_files:
      -  ../vars/vars_node.yaml
      -  ../vars/vars_hosts.yaml
  gather_facts: yes
  tasks:
    - name: Deploy and Update VM linux
      include_role:
        name: ../roles/deploy/linux
      vars:
        newid: "{{ item }}"
      loop: "{{ newid_values }}"

    - name: Deploy and Update VM windows
      include_role:
        name: ../roles/deploy/windows
      vars:
        newid: "{{ item }}"
      loop: "{{ newid_values_win }}"
    

 